In [4]:
import pandas as pd

In [11]:
pd.read_csv("https://raw.githubusercontent.com/palewire/first-python-notebook/main/docs/src/_static/ntsb-accidents.csv")

,event_id,ntsb_make,ntsb_model,ntsb_number,year,date,city,state,country,total_fatalities,latimes_make,latimes_model,latimes_make_and_model
0,20061222X01838,BELL,407,NYC07FA048,2006,12/14/2006 00:00:00,DAGSBORO,DE,USA,2,BELL,407,BELL 407
1,20060817X01187,ROBINSON,R22 BETA,LAX06LA257,2006,08/10/2006 00:00:00,TUCSON,AZ,USA,1,ROBINSON,R22,ROBINSON R22
2,20060111X00044,ROBINSON,R44,MIA06FA039,2006,01/01/2006 00:00:00,GRAND RIDGE,FL,USA,3,ROBINSON,R44,ROBINSON R44
3,20060419X00461,ROBINSON,R44 II,DFW06FA102,2006,04/13/2006 00:00:00,FREDERICKSBURG,TX,USA,2,ROBINSON,R44,ROBINSON R44
4,20060208X00181,ROBINSON,R44,SEA06LA052,2006,02/06/2006 00:00:00,HELENA,MT,USA,1,ROBINSON,R44,ROBINSON R44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,20160711X32921,BELL HELICOPTER TEXTRON CANADA,407,ERA16FA248,2016,07/11/2016 00:00:00,HICKORY,KY,USA,1,BELL,407,BELL 407
159,20160804X45514,SCHWEIZER,269C 1,CEN16FA304,2016,08/03/2016 00:00:00,JEANERETTE,LA,USA,1,SCHWEIZER,269,SCHWEIZER 269
160,20160404X74644,BELL,206,ERA16FA144,2016,04/04/2016 00:00:00,PIGEON FORGE,TN,USA,5,BELL,206,BELL 206
161,20160507X31120,AIRBUS,AS350,ANC16FA023,2016,05/06/2016 00:00:00,SKAGWAY,AK,USA,1,AIRBUS,350,AIRBUS 350
162,20160612X85856,ROBINSON HELICOPTER COMPANY,R44 II,CEN16FA215,2016,06/12/2016 00:00:00,JONESBORO,AR,USA,1,ROBINSON,R44,ROBINSON R44

In [9]:
accident_list = pd.read_csv("https://raw.githubusercontent.com/palewire/first-python-notebook/main/docs/src/_static/ntsb-accidents.csv")

In [12]:
accident_list.head()

,event_id,ntsb_make,ntsb_model,ntsb_number,year,date,city,state,country,total_fatalities,latimes_make,latimes_model,latimes_make_and_model
0,20061222X01838,BELL,407,NYC07FA048,2006,12/14/2006 00:00:00,DAGSBORO,DE,USA,2,BELL,407,BELL 407
1,20060817X01187,ROBINSON,R22 BETA,LAX06LA257,2006,08/10/2006 00:00:00,TUCSON,AZ,USA,1,ROBINSON,R22,ROBINSON R22
2,20060111X00044,ROBINSON,R44,MIA06FA039,2006,01/01/2006 00:00:00,GRAND RIDGE,FL,USA,3,ROBINSON,R44,ROBINSON R44
3,20060419X00461,ROBINSON,R44 II,DFW06FA102,2006,04/13/2006 00:00:00,FREDERICKSBURG,TX,USA,2,ROBINSON,R44,ROBINSON R44
4,20060208X00181,ROBINSON,R44,SEA06LA052,2006,02/06/2006 00:00:00,HELENA,MT,USA,1,ROBINSON,R44,ROBINSON R44

In [13]:
accident_list.head(1)

,event_id,ntsb_make,ntsb_model,ntsb_number,year,date,city,state,country,total_fatalities,latimes_make,latimes_model,latimes_make_and_model
0,20061222X01838,BELL,407,NYC07FA048,2006,12/14/2006 00:00:00,DAGSBORO,DE,USA,2,BELL,407,BELL 407

In [14]:
accident_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   event_id                163 non-null    object
 1   ntsb_make               163 non-null    object
 2   ntsb_model              163 non-null    object
 3   ntsb_number             163 non-null    object
 4   year                    163 non-null    int64
 5   date                    163 non-null    object
 6   city                    163 non-null    object
 7   state                   162 non-null    object
 8   country                 163 non-null    object
 9   total_fatalities        163 non-null    int64
 10  latimes_make            163 non-null    object
 11  latimes_model           163 non-null    object
 12  latimes_make_and_model  163 non-null    object
dtypes: int64(2), object(11)
memory usage: 16.7+ KB

In [15]:
accident_list.groupby("latimes_make_and_model")

In [16]:
accident_list.groupby("latimes_make_and_model").size()

latimes_make_and_model
AGUSTA 109                2
AIRBUS 130                1
AIRBUS 135                4
AIRBUS 350               29
BELL 206                 28
BELL 407                 13
HUGHES 369               13
MCDONNELL DOUGLAS 369     6
ROBINSON R22             20
ROBINSON R44             38
SCHWEIZER 269             5
SIKORSKY 76               2
bell 206                  2
dtype: int64

In [17]:
accident_list.groupby("latimes_make_and_model")["total_fatalities"].sum()

latimes_make_and_model
AGUSTA 109                5
AIRBUS 130                1
AIRBUS 135               11
AIRBUS 350               81
BELL 206                 58
BELL 407                 35
HUGHES 369               19
MCDONNELL DOUGLAS 369     7
ROBINSON R22             27
ROBINSON R44             71
SCHWEIZER 269             7
SIKORSKY 76              11
bell 206                  3
Name: total_fatalities, dtype: int64

***New data import + group by and count***

In [38]:
calvert_overdoses_2024 = pd.read_csv("/Users/samgauntt/Documents/GitHub/data_journalism_2025_spring/python/calvert_overdoses_2024.csv")

In [39]:
calvert_overdoses_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 12 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   FATAL/NON-FATAL                         51 non-null     object
 1   TIME                                    51 non-null     object
 2   DATE                                    51 non-null     object
 3   BLOCK                                   48 non-null     float64
 4   ROAD/CITY OF INCIDENT                   51 non-null     object
 5   ZIP CODE OF INCIDENT                    51 non-null     int64
 6   AGE                                     51 non-null     int64
 7   RACE                                    51 non-null     object
 8   SEX                                     51 non-null     object
 9   NALOXONE?                               51 non-null     object
 10  # OF DOSES                              31 non-null     float64
 11  SUSPECTED OVERDOSE DRUG/CAUSE OF DEATH  51 non-null     object
dtypes: float64(2), int64(2), object(8)
memory usage: 4.9+ KB

In [40]:
calvert_overdoses_2024.groupby("FATAL/NON-FATAL").size()

FATAL/NON-FATAL
FATAL        10
Non-fatal    41
dtype: int64

***ANSWER: In 2024, there were 10 fatal overdoses and 41 non-fatal overdoses in Calvert County, Maryland.***